
indiareads:
  db:
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/indiareads?autoReconnect=true&useSSL=false"
    username: "root"
    password: "root"
    maxconnections: 10
    minconnections: 2
    maxpartitions: 2
    maxlifetimeinmillis: 30000
    connectiontimeoutinmillis: 60000  
    
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  format_sql: true
  hbm2ddl:
    auto: update
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: false
  enable_lazy_load_no_trans: true 

org: 
  hibernate:
    envers:
      audit_table_suffix: _audit
      revision_field_name: rev
      revision_type_field_name: revtype
      revision_on_collection_change: true
      audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      audit_strategy_validity_end_rev_field_name: revend
      audit_strategy_validity_store_revend_timestamp: true
      audit_strategy_validity_revend_timestamp_field_name: revend_tstamp
